# db_manage2.py
import sqlite3
import os

DB_NAME = "food_surplus2.db"
SCHEMA_FILE = "schema2.sql"
# Check local folder first, then check sibling backend folder
LOCAL_DAT = "users.dat"
BACKEND_DAT = os.path.join("..", "backend", "users.dat")
USERS_DAT = BACKEND_DAT if os.path.exists(BACKEND_DAT) else LOCAL_DAT

class FoodSurplusDBMS:
    def __init__(self, db_path=DB_NAME):
        self.db_path = db_path
        self.init_database()

    def get_connection(self):
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        conn.execute("PRAGMA foreign_keys = ON;")
        return conn

    def init_database(self):
        """Initializes tables using schema2.sql or creates them if missing."""
        conn = self.get_connection()
        if os.path.exists(SCHEMA_FILE):
            with open(SCHEMA_FILE, "r") as f:
                conn.executescript(f.read())
        else:
            conn.executescript("""
                PRAGMA foreign_keys = ON;
                CREATE TABLE IF NOT EXISTS users (
                    id INTEGER PRIMARY KEY,
                    role TEXT NOT NULL CHECK(role IN ('DONOR', 'NGO', 'SHELTER')),
                    name TEXT NOT NULL,
                    contact TEXT NOT NULL UNIQUE,
                    address TEXT NOT NULL,
                    extra_info TEXT NOT NULL,
                    penalty_points INTEGER DEFAULT 0,
                    penalty_fines REAL DEFAULT 0.0,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                );
            """)
        conn.commit()
        conn.close()

    def sync_from_cpp(self):
        """
        Reads users.dat generated by phase2.cpp and inserts/updates SQLite.
        Does NOT delete any existing database entries.
        """
        if not os.path.exists(USERS_DAT):
            return 0

        with open(USERS_DAT, "r") as f:
            raw_lines = [l.strip() for l in f if l.strip()]

        if not raw_lines:
            return 0

        try:
            count = int(raw_lines[0])
        except ValueError:
            return 0

        conn = self.get_connection()
        cur = conn.cursor()
        synced = 0
        idx = 1

        for _ in range(count):
            if idx >= len(raw_lines):
                break

            role = raw_lines[idx].upper()
            uid = int(raw_lines[idx + 1])
            name = raw_lines[idx + 2]
            contact = raw_lines[idx + 3]
            addr = raw_lines[idx + 4]
            extra = raw_lines[idx + 5]

            # Handles both formats: single line "pts fines" or two separate lines
            line_after = raw_lines[idx + 6].split()
            if len(line_after) >= 2:
                pts = int(line_after[0])
                fines = float(line_after[1])
                idx += 7
            else:
                pts = int(line_after[0])
                fines = float(raw_lines[idx + 7])
                idx += 8

            cur.execute("""
                INSERT OR REPLACE INTO users (id, role, name, contact, address, extra_info, penalty_points, penalty_fines)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?);
            """, (uid, role, name, contact, addr, extra, pts, fines))
            synced += 1

        conn.commit()
        conn.close()
        return synced

    def sync_to_cpp(self):
        """
        Exports the merged SQLite table into users.dat so phase2.cpp
        reads all users reliably via loadFromDisk().
        """
        conn = self.get_connection()
        cur = conn.cursor()
        cur.execute("SELECT id, role, name, contact, address, extra_info, penalty_points, penalty_fines FROM users ORDER BY id ASC;")
        rows = cur.fetchall()
        conn.close()

        with open(USERS_DAT, "w", newline="\n") as f:
            f.write(f"{len(rows)}\n")
            for r in rows:
                role = r["role"].strip()
                uid = r["id"]
                name = r["name"].strip()
                contact = r["contact"].strip()
                addr = r["address"].strip()
                extra = r["extra_info"].strip() if r["extra_info"].strip() else "none"
                pts = r["penalty_points"]
                fines = float(r["penalty_fines"])

                # Exact formatting expected by phase2.cpp loadFromDisk()
                f.write(f"{role}\n")
                f.write(f"{uid}\n")
                f.write(f"{name}\n")
                f.write(f"{contact}\n")
                f.write(f"{addr}\n")
                f.write(f"{extra}\n")
                f.write(f"{pts} {fines}\n")

    def register_user_from_python(self, role, name, contact, addr, extra=""):
        """Allows registering users directly inside Python without losing C++ entries."""
        conn = self.get_connection()
        cur = conn.cursor()
        cur.execute("SELECT COALESCE(MAX(id), 0) + 1 FROM users;")
        next_id = cur.fetchone()[0]

        cur.execute("""
            INSERT INTO users (id, role, name, contact, address, extra_info, penalty_points, penalty_fines)
            VALUES (?, ?, ?, ?, ?, ?, 0, 0.0);
        """, (next_id, role.upper(), name, contact, addr, extra))
        conn.commit()
        conn.close()

        # Update users.dat immediately
        self.sync_to_cpp()
        print(f"[Python DBMS] Successfully registered {role} #{next_id}: {name}")

    def display(self):
        conn = self.get_connection()
        cur = conn.cursor()
        cur.execute("SELECT id, role, name, contact, extra_info FROM users ORDER BY id ASC;")
        rows = cur.fetchall()
        print("\n" + "=" * 65)
        print(" CURRENT DATABASE ENTITIES (food_surplus2.db)")
        print("=" * 65)
        for r in rows:
            print(f"[{r['role']}] ID #{r['id']}: {r['name']} | Ph: {r['contact']} | Info: {r['extra_info']}")
        print("=" * 65)
        conn.close()


if __name__ == "__main__":
    db = FoodSurplusDBMS()

    # Step 1: Ingest any users newly created in C++
    synced_count = db.sync_from_cpp()
    if synced_count > 0:
        print(f"[DBMS Sync] Ingested {synced_count} records from C++ (users.dat).")

    # Step 2: Seed default entities only if the database is completely empty
    conn = db.get_connection()
    c = conn.cursor()
    c.execute("SELECT COUNT(*) FROM users;")
    total = c.fetchone()[0]
    conn.close()

    if total == 0:
        print("[DBMS] First-time setup: Adding baseline seed entities...")
        db.register_user_from_python("DONOR", "Royal Orchid Banquet", "9876543210", "Rajpur Road", "Catering")
        db.register_user_from_python("NGO", "Sneha Children Home", "9123456780", "Clock Tower", "veg")
        db.register_user_from_python("SHELTER", "Paws Animal Care", "9988776655", "Subhash Nagar", "Dogs")

    # Step 3: Export unified records back to users.dat for phase2.cpp
    db.sync_to_cpp()

    # Step 4: Show current state
    db.display()
    print("\nSync complete. Both C++ and Python are now sharing the same data.")
